### ISSUE TITLE
Bug: Profile page template displays field label for select field where meta value is empty

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-member-directory#154]
**Describe the bug**
When a select type user field is created and the first option of the field has no value

**To Replicate:**

1. Create an optional select type user field, e.g. Example (example)
2. Set options for select field as:

```
:- SELECT -
option_1:Option One
option_2:Option Two
```

3. Edit the member directory's assigned profile page shortcode to display this field, e.g. `[pmpro_member_profile fields="Example,example"]`
4. Navigate to front end directory profile page of a user who has not filled in a value for this field.
5. Observe error: Value for `example` displayed is `- SELECT -`

**Expected behavior**
The custom user should not display on the profile page if there is no value for that field.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro and PMPro Member Directory plugins are active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.
